# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
