# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_catalog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='image',
            field=models.ImageField(default=0, upload_to='catalog_images'),
            preserve_default=False,
        ),
    ]
